services:
  Apps.strategyService.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.strategyService.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: ['@StrategyService.Shared.domain.CommandBus']

  Apps.strategyService.controllers.CoursesCounterGetController:
    class: ../../controllers/CoursesCounterGetController
    arguments: ['@StrategyService.Shared.domain.QueryBus']
