services:
  Apps.strategyService.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.strategyService.controllers.OrderGetController:
    class: ../../controllers/OrderGetController
    arguments: ['@StrategyService.Shared.domain.QueryBus']

  Apps.strategyService.controllers.OrderPostController:
    class: ../../controllers/OrderPostController
    arguments: ['@StrategyService.Shared.domain.QueryBus']


