services:
  Apps.alertService.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.alertService.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: ['@AlertService.Shared.domain.CommandBus']

  Apps.alertService.controllers.CoursesCounterGetController:
    class: ../../controllers/CoursesCounterGetController
    arguments: ['@AlertService.Shared.domain.QueryBus']
