services:
  StrategyService.Shared.MongoConfig:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  StrategyService.Shared.RabbitMQConfig:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  StrategyService.Shared.domain.EventBus:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@StrategyService.Shared.DomainEventFailoverPublisher',
        '@StrategyService.Shared.RabbitMQConnection',
        '@StrategyService.Shared.RabbitMQqueueFormatter',
        '@StrategyService.Shared.RabbitMQConfig'
      ]

  StrategyService.Shared.ConnectionManager:
    factory:
      class: ../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc', '@StrategyService.Shared.MongoConfig']

  StrategyService.Shared.RabbitMQQueueFormatter:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['mooc']

  StrategyService.Shared.RabbitMQConnection:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMqConnection
    arguments: ['@StrategyService.Shared.RabbitMQConfig']

  StrategyService.Shared.RabbitMQqueueFormatter:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['mooc']

  StrategyService.Shared.RabbitMQConfigurer:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQConfigurer
    arguments: ["@StrategyService.Shared.RabbitMQConnection", "@StrategyService.Shared.RabbitMQQueueFormatter"]

  StrategyService.Shared.DomainEventFailoverPublisher:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@StrategyService.Shared.ConnectionManager']

  StrategyService.Shared.CommandHandlers:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  StrategyService.Shared.domain.CommandBus:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@StrategyService.Shared.CommandHandlers']

  StrategyService.Shared.QueryHandlers:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  StrategyService.Shared.domain.QueryBus:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@StrategyService.Shared.QueryHandlers']
