services:
  Apps.pricingService.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.pricingService.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: ['@PricingService.Shared.domain.CommandBus']

  Apps.pricingService.controllers.CoursesCounterGetController:
    class: ../../controllers/CoursesCounterGetController
    arguments: ['@PricingService.Shared.domain.QueryBus']
