services:
  PricingService.CoursesCounter.CoursesCounterRepository:
    class: ../../../../Contexts/Mooc/CoursesCounter/infrastructure/persistence/mongo/MongoCoursesCounterRepository
    arguments: ['@PricingService.Shared.ConnectionManager']

  PricingService.CoursesCounter.CoursesCounterIncrementer:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Increment/CoursesCounterIncrementer
    arguments: ['@PricingService.CoursesCounter.CoursesCounterRepository', '@PricingService.Shared.domain.EventBus']

  PricingService.CoursesCounter.IncrementCoursesCounterOnCourseCreated:
    class: ../../../../Contexts/pricingService/application/Create/CreateBackofficeCourseOnCourseCreated3
    arguments: ['@PricingService.CoursesCounter.CoursesCounterIncrementer']
    tags:
      - { name: 'domainEventSubscriber' }

  PricingService.CoursesCounter.CoursesCounterFinder:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Find/CoursesCounterFinder
    arguments: ['@PricingService.CoursesCounter.CoursesCounterRepository']

  PricingService.CoursesCounter.FindCoursesCounterQueryHandler:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Find/FindCoursesCounterQueryHandler
    arguments: ['@PricingService.CoursesCounter.CoursesCounterFinder']
    tags:
      - { name: 'queryHandler' }
