services:
  AlertService.CoursesCounter.CoursesCounterRepository:
    class: ../../../../Contexts/Mooc/CoursesCounter/infrastructure/persistence/mongo/MongoCoursesCounterRepository
    arguments: ['@AlertService.Shared.ConnectionManager']

  AlertService.CoursesCounter.CoursesCounterIncrementer:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Increment/CoursesCounterIncrementer
    arguments: ['@AlertService.CoursesCounter.CoursesCounterRepository', '@AlertService.Shared.domain.EventBus']

  AlertService.CoursesCounter.IncrementCoursesCounterOnCourseCreated:
    class: ../../../../Contexts/alertService/alerts/application/Create/CreateBackofficeCourseOnCourseCreated
    arguments: ['@AlertService.CoursesCounter.CoursesCounterIncrementer']
    tags:
      - { name: 'domainEventSubscriber' }

  AlertService.CoursesCounter.CoursesCounterFinder:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Find/CoursesCounterFinder
    arguments: ['@AlertService.CoursesCounter.CoursesCounterRepository']

  AlertService.CoursesCounter.FindCoursesCounterQueryHandler:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Find/FindCoursesCounterQueryHandler
    arguments: ['@AlertService.CoursesCounter.CoursesCounterFinder']
    tags:
      - { name: 'queryHandler' }
