services:
  StrategyService.CoursesCounter.CoursesCounterRepository:
    class: ../../../../Contexts/Mooc/CoursesCounter/infrastructure/persistence/mongo/MongoCoursesCounterRepository
    arguments: ['@StrategyService.Shared.ConnectionManager']

  StrategyService.CoursesCounter.CoursesCounterIncrementer:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Increment/CoursesCounterIncrementer
    arguments: ['@StrategyService.CoursesCounter.CoursesCounterRepository', '@StrategyService.Shared.domain.EventBus']

  StrategyService.CoursesCounter.CoursesCounterFinder:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Find/CoursesCounterFinder
    arguments: ['@StrategyService.CoursesCounter.CoursesCounterRepository']

  StrategyService.CoursesCounter.FindCoursesCounterQueryHandler:
    class: ../../../../Contexts/Mooc/CoursesCounter/application/Find/FindCoursesCounterQueryHandler
    arguments: ['@StrategyService.CoursesCounter.CoursesCounterFinder']
    tags:
      - { name: 'queryHandler' }
