services:
  Apps.tradeExecutionService.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.tradeExecutionService.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: ['@TradeExecutionService.Shared.domain.CommandBus']

  Apps.tradeExecutionService.controllers.CoursesCounterGetController:
    class: ../../controllers/CoursesCounterGetController
    arguments: ['@TradeExecutionService.Shared.domain.QueryBus']
