services:
  PricingService.Courses.domain.CourseRepository:
    class: ../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@PricingService.Shared.ConnectionManager']

  PricingService.Courses.application.CourseCreator:
    class: ../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@PricingService.Courses.domain.CourseRepository', '@PricingService.Shared.domain.EventBus']

  PricingService.courses.Boom:
    class: ../../../../Contexts/pricingService/application/Create/Boom3
    tags:
      - { name: 'domainEventSubscriber' }

  PricingService.courses.CreateCourseCommandHandler:
    class: ../../../../Contexts/Mooc/Courses/application/Create/CreateCourseCommandHandler
    arguments: ['@PricingService.Courses.application.CourseCreator']
    tags:
      - { name: 'commandHandler' }
