services:
  TradeExecutionService.Courses.domain.CourseRepository:
    class: ../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@TradeExecutionService.Shared.ConnectionManager']

  TradeExecutionService.Courses.application.CourseCreator:
    class: ../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@TradeExecutionService.Courses.domain.CourseRepository', '@TradeExecutionService.Shared.domain.EventBus']

  TradeExecutionService.courses.ExecuteTradeOnTradeSignal:
    class: ../../../../Contexts/tradeExecutionService/Courses/application/services/ExecuteTradeOnTradeSignal
    tags:
      - { name: 'domainEventSubscriber' }

  TradeExecutionService.courses.CreateCourseCommandHandler:
    class: ../../../../Contexts/Mooc/Courses/application/Create/CreateCourseCommandHandler
    arguments: ['@TradeExecutionService.Courses.application.CourseCreator']
    tags:
      - { name: 'commandHandler' }
