services:
  AlertService.Shared.MongoConfig:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  AlertService.Shared.RabbitMQConfig:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  AlertService.Shared.domain.EventBus:
    factory:
      class: ../../../../Contexts/Mooc/Shared/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@AlertService.Shared.DomainEventFailoverPublisher',
        '@AlertService.Shared.RabbitMQConnection',
        '@AlertService.Shared.RabbitMQqueueFormatter',
        '@AlertService.Shared.RabbitMQConfig'
      ]

  AlertService.Shared.ConnectionManager:
    factory:
      class: ../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc', '@AlertService.Shared.MongoConfig']

  AlertService.Shared.RabbitMQQueueFormatter:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['mooc']

  AlertService.Shared.RabbitMQConnection:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMqConnection
    arguments: ['@AlertService.Shared.RabbitMQConfig']

  AlertService.Shared.RabbitMQqueueFormatter:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['mooc']

  AlertService.Shared.RabbitMQConfigurer:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQConfigurer
    arguments: ["@AlertService.Shared.RabbitMQConnection", "@AlertService.Shared.RabbitMQQueueFormatter"]

  AlertService.Shared.DomainEventFailoverPublisher:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@AlertService.Shared.ConnectionManager']

  AlertService.Shared.CommandHandlers:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  AlertService.Shared.domain.CommandBus:
    class: ../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@AlertService.Shared.CommandHandlers']

  AlertService.Shared.QueryHandlers:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  AlertService.Shared.domain.QueryBus:
    class: ../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@AlertService.Shared.QueryHandlers']
