services:
  StrategyService.orders.domain.OrderRepository:
    class: ../../../../Contexts/strategyService/orders/infrastructure/persistence/MongoOrderRepository
    arguments: ['@StrategyService.Shared.ConnectionManager']


  StrategyService.orders.CreateOrderCommandHandler:
    class: ../../../../Contexts/strategyService/orders/domain/commandHandlers/CreateOrderCommandHandler
    arguments: ['@StrategyService.orders.domain.OrderRepository', '@StrategyService.Shared.domain.EventBus']
    tags:
      - { name: 'commandHandler' }

  StrategyService.orders.FindOrdersQueryHandler:
    class: ../../../../Contexts/strategyService/orders/application/queryHandlers/FindOrdersQueryHandler
    arguments: ['@StrategyService.orders.domain.OrderRepository']
    tags:
      - { name: 'queryHandler' }

  Apps.strategyService.controllers.OrderPostController:
    class: ../../controllers/OrderPostController
    arguments: ['@StrategyService.Shared.domain.CommandBus']

  Apps.strategyService.controllers.OrderDeleteController:
    class: ../../controllers/OrderDeleteController
    arguments: ['@StrategyService.Shared.domain.CommandBus']

  StrategyService.orders.DeleteOrderCommandHandler:
    class: ../../../../Contexts/strategyService/orders/domain/commandHandlers/DeleteOrderCommandHandler
    arguments: ['@StrategyService.orders.domain.OrderRepository']
    tags:
      - { name: 'commandHandler' }




  
