services:
  AlertService.Courses.domain.CourseRepository:
    class: ../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@AlertService.Shared.ConnectionManager']

  AlertService.Courses.application.CourseCreator:
    class: ../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@AlertService.Courses.domain.CourseRepository', '@AlertService.Shared.domain.EventBus']

  AlertService.courses.Boom:
    class: ../../../../Contexts/alertService/alerts/application/Create/Boom
    tags:
      - { name: 'domainEventSubscriber' }

  AlertService.courses.CreateCourseCommandHandler:
    class: ../../../../Contexts/Mooc/Courses/application/Create/CreateCourseCommandHandler
    arguments: ['@AlertService.Courses.application.CourseCreator']
    tags:
      - { name: 'commandHandler' }
