services:
  AlertService.Courses.domain.CourseRepository:
    class: ../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@AlertService.Shared.ConnectionManager']

  AlertService.alerts.domain.AlertRepository:
    class: ../../../../Contexts/alertService/alerts/infrastructure/persistence/MongoAlertRepository
    arguments: ['@AlertService.Shared.ConnectionManager']

  AlertService.Courses.application.CourseCreator:
    class: ../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@AlertService.Courses.domain.CourseRepository', '@AlertService.Shared.domain.EventBus']

  AlertService.courses.Boom:
    class: ../../../../Contexts/alertService/alerts/application/Create/Boom
    arguments: ['@AlertService.alerts.domain.AlertRepository']
    tags:
      - { name: 'domainEventSubscriber' }

  AlertService.courses.CreateAlertsOnOrderPlacedEvent:
    class: ../../../../Contexts/alertService/alerts/application/eventHandlers/CreateAlertsOnOrderPlacedEvent
    arguments: ['@AlertService.alerts.domain.AlertRepository']
    tags:
      - { name: 'domainEventSubscriber' }
  
  AlertService.courses.TriggerAlertOnPriceUpdateDomainEvent:
   class: ../../../../Contexts/alertService/alerts/application/eventHandlers/TriggerAlertOnPriceUpdateDomainEvent
   arguments: ['@AlertService.alerts.domain.AlertRepository', '@AlertService.Shared.domain.EventBus']
   tags:
     - { name: 'domainEventSubscriber' }


  AlertService.courses.CreateCourseCommandHandler:
    class: ../../../../Contexts/Mooc/Courses/application/Create/CreateCourseCommandHandler
    arguments: ['@AlertService.Courses.application.CourseCreator']
    tags:
      - { name: 'commandHandler' }

  AlertService.courses.CreateAlertCommandHandler:
    class: ../../../../Contexts/alertService/alerts/application/commandHandlers/CreateAlertCommandHandler
    arguments: ['@AlertService.alerts.domain.AlertRepository']
    tags:
      - { name: 'commandHandler' }
  AlertService.courses.FindAlertsQueryHandler:
    class: ../../../../Contexts/alertService/alerts/application/queryHandlers/FindAlertsQueryHandler
    arguments: ['@AlertService.alerts.domain.AlertRepository']
    tags:
      - { name: 'queryHandler' }
